### ISSUE TITLE
problem in php 7

### ISSUE THREAD

**Issue by godgiven-project** [PaoloDuzioni/PHP-Gettext-Translation-Example#1]
I run PHP-Gettext-Translation-Example this is **very good in PHP 5** but when I run PHP-Gettext-Translation-Example **in PHP 7 get me this error**:

Internal Server Error
Methods with the same name as their class will not be constructors in a future version of PHP; StringReader has a deprecated constructor

**Comment by ardalanfp** [comment]
see this link:
https://stackoverflow.com/a/42819581/5705051

**Comment by godgiven-project** [comment]
it's really good. I used this and it worked.
